#FROM ubuntu:18.04
FROM python:3.8
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
COPY . /app/
WORKDIR /app
ENV FLASK_ENV='dev'
ENV AIP_HTTP_PORT=5000
EXPOSE 5000
ENTRYPOINT ["python", "-m", "server"]
