name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'server.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'server.py'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --file ./docker/dockerfile --tag ${{secrets.DOCKER_USER}}/notchess:latest
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/notchess:latest
