name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: $(( secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - name: Build the Docker image
      run: docker build . --file ./docker/dockerfile --tag $DOCER_USER/not_chess:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/not_chess
